package net.lanbridge.android;
import org.junit.Test;
import static org.junit.Assert.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.io.*;

public class ConfigBackupCodecTest {
 private JSONObject vector()throws Exception{try(InputStream in=getClass().getResourceAsStream("/config_snapshot_v2.json")){return new JSONObject(new String(in.readAllBytes(),StandardCharsets.UTF_8));}}
 @Test public void decryptsWindowsVector()throws Exception{JSONObject v=vector();assertTrue(LedgerStore.equivalent(v.getJSONObject("payload"),ConfigBackupCodec.decrypt(v.getJSONObject("envelope"),v.getString("password"))));}
 @Test public void androidVectorAndUnicodePassword()throws Exception{JSONObject v=vector(),p=ConfigBackupCodec.payload("android",AndroidConfigBackup.create(new JSONObject().put("favorite.ledger",true),"https://nas.invalid","sample-user","lan"),v.getJSONObject("payload").getJSONObject("ai"));p.put("created_at",1790488800);p.getJSONObject("config").put("created_at",1790488800);byte[] salt=new byte[16],nonce=new byte[12];for(int i=0;i<salt.length;i++)salt[i]=(byte)i;for(int i=0;i<nonce.length;i++)nonce[i]=(byte)(i+16);String password="fixture-安卓-password";JSONObject encrypted=ConfigBackupCodec.encrypt(p,password,salt,nonce);assertTrue(LedgerStore.equivalent(p,ConfigBackupCodec.decrypt(encrypted,password)));Path target=Paths.get("build/config_snapshot_android_v2.json");Files.createDirectories(target.getParent());Files.write(target,new JSONObject().put("password",password).put("payload",p).put("envelope",encrypted).toString(2).getBytes(StandardCharsets.UTF_8));}
 @Test public void wrongPasswordTamperAndUnknownFieldsRejected()throws Exception{JSONObject v=vector(),e=v.getJSONObject("envelope");try{ConfigBackupCodec.decrypt(e,"wrong");fail();}catch(IOException expected){}String cipher=e.getString("ciphertext");e.put("ciphertext",(cipher.charAt(0)=='A'?"B":"A")+cipher.substring(1));try{ConfigBackupCodec.decrypt(e,v.getString("password"));fail();}catch(IOException expected){}e=v.getJSONObject("envelope");e.put("surprise",true);try{ConfigBackupCodec.decrypt(e,v.getString("password"));fail();}catch(IOException expected){}JSONObject p=v.getJSONObject("payload");p.put("ledger",new JSONObject());try{ConfigBackupCodec.validate(p);fail();}catch(IOException expected){}}
 @Test public void preservesAbsentParcelRolesWithProviderKeyCollision()throws Exception{JSONObject incoming=vector().getJSONObject("payload").getJSONObject("ai"),local=new JSONObject(incoming.toString());String id=local.getJSONArray("providers").getJSONObject(0).getString("id");local.getJSONObject("roles").put("parcel",new JSONObject().put("provider_id",id).put("model","parcel-model")).put("parcel_vision",new JSONObject().put("provider_id",id).put("model","vision-model"));local.getJSONObject("secrets").put(id,"local-only-key");JSONObject merged=ConfigBackupCodec.mergeAndroidRoles(incoming,local);String clone=merged.getJSONObject("roles").getJSONObject("parcel").getString("provider_id");assertNotEquals(id,clone);assertTrue(clone.startsWith("preserved-"));assertEquals(clone,merged.getJSONObject("roles").getJSONObject("parcel_vision").getString("provider_id"));assertEquals("local-only-key",merged.getJSONObject("secrets").getString(clone));assertEquals(incoming.getJSONObject("secrets").getString(id),merged.getJSONObject("secrets").getString(id));}
 @Test public void incomingParcelRoleWinsAndIdenticalProvidersReuse()throws Exception{JSONObject incoming=vector().getJSONObject("payload").getJSONObject("ai"),local=new JSONObject(incoming.toString());String id=local.getJSONArray("providers").getJSONObject(0).getString("id");local.getJSONObject("roles").put("parcel",new JSONObject().put("provider_id",id).put("model","old"));JSONObject merged=ConfigBackupCodec.mergeAndroidRoles(incoming,local);assertEquals(id,merged.getJSONObject("roles").getJSONObject("parcel").getString("provider_id"));assertEquals(incoming.getJSONArray("providers").length(),merged.getJSONArray("providers").length());incoming.getJSONObject("roles").put("parcel",new JSONObject().put("provider_id",id).put("model","new"));assertEquals("new",ConfigBackupCodec.mergeAndroidRoles(incoming,local).getJSONObject("roles").getJSONObject("parcel").getString("model"));}
}
