package net.lanbridge.android;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

public class DataSyncManagerTest {
 static class Memory implements DataSyncManager.StateStore {Map<String,Long> times=new ConcurrentHashMap<>();Map<String,String> errors=new ConcurrentHashMap<>(),identities=new ConcurrentHashMap<>();public String identity(String id){return identities.getOrDefault(id,"");}public void identity(String id,String value){identities.put(id,value);}public long time(String id){return times.getOrDefault(id,0L);}public String error(String id){return errors.getOrDefault(id,"");}public void save(String id,long success,String error){times.put(id,success);errors.put(id,error);}}
 void idle(DataSyncManager m)throws Exception{CountDownLatch done=new CountDownLatch(1);m.execute(done::countDown);assertTrue(done.await(5,TimeUnit.SECONDS));}
 @Test public void queuedTriggersCoalesceAndActiveChangesHaveOneFollowup()throws Exception{Memory state=new Memory();ScheduledExecutorService worker=Executors.newSingleThreadScheduledExecutor();DataSyncManager m=new DataSyncManager(state,worker,false);AtomicInteger calls=new AtomicInteger();CountDownLatch start=new CountDownLatch(1),release=new CountDownLatch(1),gate=new CountDownLatch(1);worker.execute(()->{try{gate.await();}catch(Exception ignored){}});m.register("test","测试",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize()throws Exception{int n=calls.incrementAndGet();if(n==1){start.countDown();assertTrue(release.await(5,TimeUnit.SECONDS));}return "ok";}});try{for(int i=0;i<50;i++)m.requestAll(DataSyncManager.Trigger.STARTUP);gate.countDown();assertTrue(start.await(5,TimeUnit.SECONDS));for(int i=0;i<50;i++){m.requestAll(DataSyncManager.Trigger.MANUAL);m.requestAll(DataSyncManager.Trigger.PERIODIC);}release.countDown();idle(m);assertEquals(1,calls.get());CountDownLatch changed=new CountDownLatch(1);m.register("editor","修改",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize(){for(int i=0;i<50;i++)if(changed.getCount()>0)m.request("editor",DataSyncManager.Trigger.LOCAL_CHANGE);changed.countDown();calls.incrementAndGet();return "ok";}});m.request("editor",DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(3,calls.get());assertFalse(m.running);assertTrue(m.lastSuccess>0);}finally{m.shutdown();}}
 @Test public void configuredFailureAndServiceFailurePersistWithoutStuckQueue()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);AtomicInteger phase=new AtomicInteger();m.register("test","测试",new DataSyncManager.Service(){public boolean configured(){if(phase.get()==0)throw new IllegalStateException("配置错误");return true;}public String synchronize()throws Exception{if(phase.get()==1)throw new Exception("离线");return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertFalse(m.running);assertTrue(m.error.contains("配置错误"));phase.set(1);m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertTrue(state.error("all").contains("离线"));assertEquals(0,m.lastSuccess);phase.set(2);m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertEquals("",m.error);assertTrue(state.time("all")>0);}finally{m.shutdown();}}
 @Test public void otherServiceSuccessDoesNotEraseFailureAndReloadKeepsStatus()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);m.register("bad","失败",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize()throws Exception{throw new Exception("offline");}});m.register("good","成功",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize(){return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);m.request("good",DataSyncManager.Trigger.MANUAL);idle(m);assertTrue(m.error.contains("offline"));DataSyncManager reload=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);try{assertEquals(m.error,reload.error);assertEquals(m.lastSuccess,reload.lastSuccess);}finally{reload.shutdown();}}finally{m.shutdown();}}

 @Test public void aggregateRequiresEveryConfiguredServiceAndUsesOldestSuccess()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);DataSyncManager.Service good=new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize(){return "ok";}};m.register("first","First",good);m.register("second","Second",good);m.register("unused","Unused",new DataSyncManager.Service(){public boolean configured(){return false;}public String synchronize(){throw new AssertionError();}});state.save("unused",0,"obsolete error");try{m.request("first",DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(0,m.lastSuccess);assertEquals("",m.error);long first=state.time("first");m.request("second",DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(first,m.lastSuccess);assertEquals("",m.error);m.request("second",DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(first,m.lastSuccess);}finally{m.shutdown();}}
 @Test public void changedConnectionClearsStatusAndRejectsInflightOldSuccess()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);AtomicReference<String> identity=new AtomicReference<>("old");CountDownLatch oldStarted=new CountDownLatch(1),oldRelease=new CountDownLatch(1),newStarted=new CountDownLatch(1),newRelease=new CountDownLatch(1);AtomicInteger calls=new AtomicInteger();m.register("test","Test",new DataSyncManager.Service(){public boolean configured(){return true;}public String identity(){return identity.get();}public String synchronize()throws Exception{if(calls.incrementAndGet()==1){oldStarted.countDown();oldRelease.await(5,TimeUnit.SECONDS);}else{newStarted.countDown();newRelease.await(5,TimeUnit.SECONDS);}return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);assertTrue(oldStarted.await(5,TimeUnit.SECONDS));identity.set("new-password-and-root");m.invalidate();assertEquals(0,m.lastSuccess);assertEquals("",m.error);oldRelease.countDown();assertTrue(newStarted.await(5,TimeUnit.SECONDS));assertEquals(0,state.time("test"));assertEquals(0,m.lastSuccess);newRelease.countDown();idle(m);assertTrue(m.lastSuccess>0);assertEquals(2,calls.get());assertEquals("new-password-and-root",state.identity("test"));}finally{oldRelease.countDown();newRelease.countDown();m.shutdown();}}
 @Test public void pendingLocalChangeDoesNotAdvanceGlobalSuccess()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false);CountDownLatch second=new CountDownLatch(1),release=new CountDownLatch(1);AtomicInteger calls=new AtomicInteger();m.register("test","Test",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize()throws Exception{if(calls.incrementAndGet()==1)m.request("test",DataSyncManager.Trigger.LOCAL_CHANGE);else{second.countDown();release.await(5,TimeUnit.SECONDS);}return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);assertTrue(second.await(5,TimeUnit.SECONDS));assertTrue(state.time("test")>0);assertEquals(0,m.lastSuccess);release.countDown();idle(m);assertTrue(m.lastSuccess>0);}finally{release.countDown();m.shutdown();}}
 @Test public void failureRetryIsBoundedAndFrequentEditsCannotBypassBackoff()throws Exception{assertEquals(5000,DataSyncManager.retryDelay(1,5000,300000));assertEquals(300000,DataSyncManager.retryDelay(50,5000,300000));Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false,10,200,1000);AtomicInteger calls=new AtomicInteger();CountDownLatch retried=new CountDownLatch(1);m.register("test","Test",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize()throws Exception{if(calls.incrementAndGet()==1)throw new Exception("offline");retried.countDown();return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(1,calls.get());for(int i=0;i<100;i++)m.requestAll(DataSyncManager.Trigger.LOCAL_CHANGE);idle(m);assertEquals(1,calls.get());assertTrue(retried.await(3,TimeUnit.SECONDS));idle(m);assertEquals(2,calls.get());assertEquals("",m.error);}finally{m.shutdown();}}
 @Test public void rapidLocalChangesDebounceIntoOneRequest()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false,100,200,1000);AtomicInteger calls=new AtomicInteger();CountDownLatch done=new CountDownLatch(1);m.register("test","Test",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize(){calls.incrementAndGet();done.countDown();return "ok";}});try{for(int i=0;i<100;i++)m.requestAll(DataSyncManager.Trigger.LOCAL_CHANGE);idle(m);assertEquals(0,calls.get());assertTrue(done.await(3,TimeUnit.SECONDS));idle(m);assertEquals(1,calls.get());}finally{m.shutdown();}}

 @Test public void explicitManualRetryRunsImmediatelyDuringAutomaticBackoff()throws Exception{Memory state=new Memory();DataSyncManager m=new DataSyncManager(state,Executors.newSingleThreadScheduledExecutor(),false,1000,5000,300000);AtomicInteger calls=new AtomicInteger();m.register("test","Test",new DataSyncManager.Service(){public boolean configured(){return true;}public String synchronize()throws Exception{if(calls.incrementAndGet()==1)throw new Exception("offline");return "ok";}});try{m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(1,calls.get());m.requestAll(DataSyncManager.Trigger.MANUAL);idle(m);assertEquals(2,calls.get());assertTrue(m.lastSuccess>0);}finally{m.shutdown();}}
}
