package net.lanbridge.android;
import androidx.appcompat.app.AlertDialog;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.File;

public final class DiagnosticsFragment extends ToolFragment {
    private LinearLayout body;private EditText target,port,timeout,attempts;private TextView output;private Button run;private LedgerSync sync;private JSONObject selected;
    @Override protected View createContent(Bundle state){sync=LedgerSync.get(context());ScrollView scroll=new ScrollView(context());body=ToolUi.column(context());body.setPadding(ToolUi.dp(context(),20),ToolUi.dp(context(),16),ToolUi.dp(context(),20),ToolUi.dp(context(),24));scroll.addView(body);LinearLayout heading=ToolUi.header(context(),"网络诊断",this::closePage);heading.addView(ToolUi.iconButton(context(),"folder","诊断配置",this::profileActions));body.addView(heading);LinearLayout root=body;ToolUi.Grid sections=new ToolUi.Grid(context(),300,2,16);root.addView(sections);body=ToolUi.card(context());sections.addView(body);
        body.addView(ToolUi.text(context(),"检查 DNS、TCP、TLS 和 HTTP。报告保存在本机，诊断使用直连网络。",14,ToolUi.MUTED));
        target=ToolUi.field(context(),body,"主机 / HTTP(S) URL","",false);LinearLayout advanced=ToolUi.column(context());advanced.setVisibility(View.GONE);body.addView(ToolUi.button(context(),"诊断参数",false,()->advanced.setVisibility(advanced.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE)));body.addView(advanced);
        port=ToolUi.field(context(),advanced,"端口（可选）","",false);timeout=ToolUi.field(context(),advanced,"超时（毫秒）","5000",false);attempts=ToolUi.field(context(),advanced,"TCP 尝试次数","3",false);
        run=ToolUi.button(context(),"开始诊断",true,this::run);body.addView(run);
        body=ToolUi.card(context());sections.addView(body);LinearLayout reportHeading=new LinearLayout(context());reportHeading.setGravity(Gravity.CENTER_VERTICAL);reportHeading.addView(ToolUi.text(context(),"诊断报告",20,ToolUi.INK),new LinearLayout.LayoutParams(0,-2,1));reportHeading.addView(ToolUi.iconButton(context(),"copy","复制报告",()->{((android.content.ClipboardManager)context().getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("网络诊断",output.getText()));Toast.makeText(context(),"已复制",0).show();}));body.addView(reportHeading);output=ToolUi.text(context(),"输入目标地址，开始检查连接。",14,ToolUi.MUTED);output.setLineSpacing(ToolUi.dp(context(),5),1);output.setTextIsSelectable(true);ToolUi.space(body,output);
        try{File last=new File(context().getFilesDir(),"diagnostic-last.json");if(last.isFile())show(LedgerStore.read(last));}catch(Exception ignored){}return scroll;
    }
    private void profileActions(){new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("诊断配置").setItems(selected==null?new String[]{"读取共享配置","保存当前配置","使用 WebDAV 地址"}:new String[]{"读取共享配置","保存当前配置","使用 WebDAV 地址","新建配置","处理配置冲突","删除当前配置"},(dialog,index)->{switch(index){case 0:profiles();break;case 1:save();break;case 2:target.setText(WebDavSettings.store(context()).origin());break;case 3:selected=null;target.setText("");port.setText("");timeout.setText("5000");attempts.setText("3");break;case 4:LedgerConflicts.show(context(),sync,"network_profile",selected.optString("id"),()->{try{applyProfile(sync.store().entity("network_profile",selected.getString("id")));}catch(Exception e){error(e);}});break;case 5:new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("删除共享配置？").setMessage("删除会同步到其他设备，历史报告保留。").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{try{sync.store().patch("network_profile",selected.getString("id"),new JSONObject(),true);sync.changed();selected=null;}catch(Exception e){error(e);}}).show();break;}}).show();}
    private void error(Exception e){Toast.makeText(context(),e.getMessage(),1).show();}
    private JSONObject value()throws Exception{String url=target.getText().toString().trim();NetworkDiagnostics.target(url);String p=port.getText().toString().trim();int t=Integer.parseInt(timeout.getText().toString().trim()),a=Integer.parseInt(attempts.getText().toString().trim()),n=p.isEmpty()?0:Integer.parseInt(p);if(t<1000||t>15000||a<1||a>5||n<0||n>65535)throw new IllegalArgumentException("请检查端口、超时和次数范围");return new JSONObject().put("target",url).put("port",n==0?JSONObject.NULL:n).put("timeout_ms",t).put("attempts",a);}
    private void run(){try{JSONObject profile=value();run.setEnabled(false);output.setText("正在检查…");new Thread(()->{try{JSONObject report=NetworkDiagnostics.run(profile.getString("target"),profile.optInt("port",0),profile.getInt("timeout_ms"),profile.getInt("attempts"));LedgerStore.write(new File(context().getFilesDir(),"diagnostic-last.json"),report.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));runOnUiThread(()->{show(report);run.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{error(e);run.setEnabled(true);});}},"network-diagnostics").start();}catch(Exception e){error(e);}}
    private void show(JSONObject report){try{StringBuilder text=new StringBuilder(report.getString("target")+"\n"+report.getString("started_at")+"\n\n");JSONArray steps=report.getJSONArray("steps");for(int i=0;i<steps.length();i++){JSONObject step=steps.getJSONObject(i);text.append(step.getString("name").toUpperCase(java.util.Locale.ROOT)).append(" · ").append(step.getString("status")).append(" · ").append(step.getLong("duration_ms")).append(" ms\n").append(step.getString("detail")).append("\n\n");}text.append(report.getString("summary"));output.setText(text);}catch(Exception e){error(e);}}
    private void save(){try{JSONObject values=value();EditText name=new EditText(context());name.setHint("配置名称");name.setText(selected==null?"":selected.optString("name"));final JSONObject base=selected;new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("保存共享诊断配置").setView(name).setPositiveButton("保存",(d,w)->{try{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException("请输入名称");values.put("name",n);JSONObject changes=new JSONObject();for(String key:LedgerStore.keys(values))if(base==null||!LedgerStore.equivalent(values.opt(key),base.opt(key)))changes.put(key,values.get(key));String id=base==null?LedgerStore.id():base.getString("id");if(changes.length()>0)sync.store().patch("network_profile",id,changes,false,base==null?new JSONArray():base.getJSONArray("_heads"));selected=sync.store().entity("network_profile",id);sync.changed();Toast.makeText(context(),"已保存，将自动同步",0).show();}catch(Exception e){error(e);}}).setNegativeButton("取消",null).show();}catch(Exception e){error(e);}}
    private void profiles(){try{JSONArray profiles=sync.store().list("network_profile");String[] names=new String[profiles.length()];for(int i=0;i<names.length;i++)names[i]=profiles.getJSONObject(i).optString("name")+(profiles.getJSONObject(i).getJSONObject("_conflicts").length()>0?" ⚠ 冲突":"");new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("共享诊断配置").setItems(names,(d,index)->{try{applyProfile(profiles.getJSONObject(index));}catch(Exception e){error(e);}}).setNegativeButton("关闭",null).show();}catch(Exception e){error(e);}}
    private void applyProfile(JSONObject p)throws Exception{selected=p;target.setText(p.getString("target"));port.setText(p.isNull("port")?"":p.optString("port"));timeout.setText(p.optString("timeout_ms","5000"));attempts.setText(p.optString("attempts","3"));}
}
