package net.lanbridge.android;
import androidx.appcompat.app.AlertDialog;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.os.*;
import android.provider.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;

public final class LedgerFragment extends ToolFragment {
    private LedgerSync sync;private LinearLayout body,rows,attachments;private TextView syncText;private Spinner projectFilter;
    private EditText start,end;private final List<String> projectIds=new ArrayList<>();private String selectedProject=LedgerStore.AI_PROJECT;
    private JSONObject original,draft;private String editingId,cameraName;private EditText title,date,amount,category,notes;private Spinner project,currency,type,status;private Button commitButton;private int importing;
    private final List<String> editProjectIds=new ArrayList<>();private final Handler handler=new Handler(Looper.getMainLooper());private long seen=-1;
    private final Runnable refresh=new Runnable(){public void run(){if(seen!=sync.revision){seen=sync.revision;render();}handler.postDelayed(this,700);}};
    @Override protected View createContent(Bundle saved){
        sync=LedgerSync.get(context());ScrollView scroll=new ScrollView(context());body=ToolUi.column(context());body.setPadding(ToolUi.dp(context(),20),ToolUi.dp(context(),16),ToolUi.dp(context(),20),ToolUi.dp(context(),24));scroll.addView(body);
        LinearLayout header=ToolUi.header(context(),"项目记账",this::closePage);body.addView(header);
        header.addView(ToolUi.iconButton(context(),"folder","项目管理",this::projects));header.addView(ToolUi.iconButton(context(),"plus","新建记账",()->edit(null)));

        LinearLayout filters=ToolUi.card(context());ToolUi.space(body,filters);projectFilter=ToolUi.spinner(context());filters.addView(projectFilter,new LinearLayout.LayoutParams(-1,ToolUi.dp(context(),52)));projectFilter.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(pos<projectIds.size()){selectedProject=projectIds.get(pos);renderRows();}}});
        ToolUi.Grid dates=new ToolUi.Grid(context(),135,2,12);filters.addView(dates);LinearLayout from=ToolUi.column(context()),to=ToolUi.column(context());dates.addView(from);dates.addView(to);
        start=ToolUi.field(context(),from,"开始日期",LocalDate.now().withDayOfMonth(1).toString(),false);end=ToolUi.field(context(),to,"结束日期",LocalDate.now().toString(),false);
        dateField(start,this::renderRows);dateField(end,this::renderRows);
        com.google.android.material.chip.ChipGroup ranges=new com.google.android.material.chip.ChipGroup(context());ranges.setSingleSelection(true);ToolUi.space(filters,ranges);
        String[] labels={"本月","近3月","半年","全部"};int[] months={1,3,6,0};for(int i=0;i<labels.length;i++){final int n=months[i];com.google.android.material.chip.Chip chip=new com.google.android.material.chip.Chip(context());chip.setText(labels[i]);chip.setCheckable(true);chip.setChecked(n==1);chip.setOnClickListener(v->{LocalDate today=LocalDate.now();start.setText(n==0?"":today.minusMonths(n-1).withDayOfMonth(1).toString());end.setText(n==0?"":today.toString());renderRows();});ranges.addView(chip);}
        rows=ToolUi.column(context());body.addView(rows);render();
        if(saved!=null){selectedProject=saved.getString("selectedProject",LedgerStore.AI_PROJECT);cameraName=saved.getString("cameraName");String raw=saved.getString("draft");if(raw!=null)try{draft=new JSONObject(raw);original=new JSONObject(saved.getString("original","{}"));editingId=saved.getString("editingId");body.post(()->showEditor());}catch(Exception ignored){}}
        return scroll;
    }
    private void action(LinearLayout parent,String text,Runnable action){Button b=ToolUi.button(context(),text,text.equals("新建记账"),action);LinearLayout.LayoutParams lp=parent.getOrientation()==LinearLayout.HORIZONTAL?new LinearLayout.LayoutParams(0,-2,1):new LinearLayout.LayoutParams(-1,-2);lp.topMargin=ToolUi.dp(context(),8);if(parent.getOrientation()==LinearLayout.HORIZONTAL&&parent.getChildCount()>0)lp.leftMargin=ToolUi.dp(context(),8);parent.addView(b,lp);}

    private void error(Exception e){Toast.makeText(context(),e.getMessage(),Toast.LENGTH_LONG).show();}
    private void render(){try{JSONArray projects=sync.store().list("project");List<String> names=new ArrayList<>();projectIds.clear();names.add("全部项目");projectIds.add("all");for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);names.add(p.optString("name","未命名项目")+(p.optBoolean("archived")?"（归档）":""));projectIds.add(p.getString("id"));}projectFilter.setAdapter(ToolUi.choices(context(),names));projectFilter.setSelection(Math.max(0,projectIds.indexOf(selectedProject)));renderRows();}catch(Exception e){error(e);}}
    private static String field(JSONObject o,String key,String fallback){return o.optString(key,fallback);}
    private void renderRows(){if(rows==null)return;rows.removeAllViews();try{
        String from=start.getText().toString().trim(),to=end.getText().toString().trim();if(!from.isEmpty())LocalDate.parse(from);if(!to.isEmpty())LocalDate.parse(to);if(!from.isEmpty()&&!to.isEmpty()&&from.compareTo(to)>0)throw new IllegalArgumentException("开始日期不能晚于结束日期");
        JSONArray list=sync.store().list("entry");List<JSONObject> entries=new ArrayList<>();for(int i=0;i<list.length();i++){JSONObject e=list.getJSONObject(i);String d=e.optString("date");if(!selectedProject.equals("all")&&!selectedProject.equals(e.optString("project_id",LedgerStore.AI_PROJECT)))continue;if(!from.isEmpty()&&d.compareTo(from)<0||!to.isEmpty()&&d.compareTo(to)>0)continue;entries.add(e);}entries.sort((a,b)->b.optString("date").compareTo(a.optString("date")));
        Map<String,BigDecimal[]> totals=new LinkedHashMap<>();for(JSONObject e:entries){BigDecimal[] t=totals.computeIfAbsent(e.optString("currency","CNY"),k->new BigDecimal[]{BigDecimal.ZERO,BigDecimal.ZERO});int at=e.optString("entry_type").equals("income")?0:1;t[at]=t[at].add(new BigDecimal(e.optString("amount","0")));}
        for(Map.Entry<String,BigDecimal[]> total:totals.entrySet()){LinearLayout summary=ToolUi.card(context());ToolUi.space(rows,summary);summary.addView(ToolUi.text(context(),total.getKey()+" · 区间收支",13,ToolUi.MUTED));ToolUi.Grid stats=new ToolUi.Grid(context(),120,2,12);summary.addView(stats);String[] captions={"收入","支出"};for(int i=0;i<2;i++){LinearLayout stat=ToolUi.column(context());stat.setPadding(0,ToolUi.dp(context(),12),0,0);stat.addView(ToolUi.text(context(),captions[i],13,ToolUi.MUTED));TextView number=ToolUi.text(context(),total.getValue()[i].setScale(2).toPlainString(),24,i==0?0xff21836d:ToolUi.INK);number.setTypeface(null,android.graphics.Typeface.BOLD);stat.addView(number);stats.addView(stat);}}
        TextView countLabel=ToolUi.text(context(),entries.size()+" 条记录",13,ToolUi.MUTED);ToolUi.space(rows,countLabel);
        String lastDate="";for(JSONObject e:entries){String day=e.optString("date");if(!day.equals(lastDate)){TextView dateLabel=ToolUi.text(context(),day,14,ToolUi.MUTED);dateLabel.setTypeface(null,android.graphics.Typeface.BOLD);ToolUi.space(rows,dateLabel);lastDate=day;}
            boolean income=e.optString("entry_type").equals("income");LinearLayout card=ToolUi.card(context());ToolUi.space(rows,card);LinearLayout top=new LinearLayout(context());top.setGravity(Gravity.CENTER_VERTICAL);card.addView(top);
            TextView name=ToolUi.text(context(),e.optString("title","未命名"),17,ToolUi.INK);name.setTypeface(null,android.graphics.Typeface.BOLD);name.setMaxLines(2);name.setEllipsize(android.text.TextUtils.TruncateAt.END);top.addView(name,new LinearLayout.LayoutParams(0,-2,1));
            TextView money=ToolUi.text(context(),(income?"+":"−")+e.optString("amount","0.00"),20,income?0xff21836d:ToolUi.INK);money.setTypeface(null,android.graphics.Typeface.BOLD);money.setPadding(ToolUi.dp(context(),12),0,0,0);top.addView(money);
            JSONObject group=sync.store().entity("project",e.optString("project_id",LedgerStore.AI_PROJECT));String meta=group.optString("name","项目")+" · "+e.optString("category","其他")+" · "+e.optString("currency","CNY");TextView details=ToolUi.text(context(),meta,13,ToolUi.MUTED);ToolUi.space(card,details);if(!income&&group.optString("settlement_mode",e.optString("project_id").equals(LedgerStore.AI_PROJECT)?"half":"general").equals("half"))ToolUi.space(card,ToolUi.text(context(),"分摊金额 "+new BigDecimal(e.optString("amount","0.00")).divide(new BigDecimal("2"),2,java.math.RoundingMode.HALF_UP).toPlainString()+" "+e.optString("currency","CNY"),13,ToolUi.MUTED));
            LinearLayout bottom=new LinearLayout(context());bottom.setGravity(Gravity.CENTER_VERTICAL);ToolUi.space(card,bottom);String state=income?"收入":e.optString("status").equals("reimbursed")?"已报销":e.optString("status").equals("non_reimbursable")?"不报销":"待报销";TextView badge=ToolUi.badge(context(),state,income?0xff21836d:ToolUi.BLUE);bottom.addView(badge);
            int count=0;for(String k:LedgerStore.keys(e))if(k.startsWith("attachment:")&&!e.isNull(k))count++;TextView attached=ToolUi.text(context(),count>0?count+" 个附件":"",12,ToolUi.MUTED);attached.setGravity(Gravity.END);bottom.addView(attached,new LinearLayout.LayoutParams(0,-2,1));
            if(e.getJSONObject("_conflicts").length()>0)ToolUi.space(card,ToolUi.text(context(),"存在并发修改 · 点按处理",13,0xffb44935));
            card.setFocusable(true);card.setContentDescription("编辑记账 "+e.optString("title"));card.setOnClickListener(v->edit(e));
        }
        if(entries.isEmpty()){LinearLayout empty=ToolUi.card(context());ToolUi.space(rows,empty);empty.setGravity(Gravity.CENTER);empty.addView(ToolUi.icon(context(),"ledger",ToolUi.MUTED),new LinearLayout.LayoutParams(ToolUi.dp(context(),40),ToolUi.dp(context(),40)));ToolUi.space(empty,ToolUi.text(context(),"这段时间还没有记录",17,ToolUi.INK));empty.addView(ToolUi.button(context(),"新建记账",true,()->edit(null)));}
    }catch(Exception e){rows.addView(ToolUi.text(context(),e.getMessage(),14,0xffb03030));}}
    private void dateField(EditText field,Runnable changed){field.setFocusable(false);field.setOnClickListener(v->{LocalDate value;try{value=LocalDate.parse(field.getText());}catch(Exception ignored){value=LocalDate.now();}new DatePickerDialog(context(),(picker,y,m,d)->{field.setText(LocalDate.of(y,m+1,d).toString());changed.run();},value.getYear(),value.getMonthValue()-1,value.getDayOfMonth()).show();});}
    private void projects(){try{JSONArray list=sync.store().list("project");List<String> names=new ArrayList<>();for(int i=0;i<list.length();i++)names.add(list.getJSONObject(i).optString("name")+(list.getJSONObject(i).getJSONObject("_conflicts").length()>0?" ⚠ 冲突":""));names.add("＋ 创建项目组");new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("项目组").setItems(names.toArray(new String[0]),(d,n)->{try{editProject(n==list.length()?null:list.getJSONObject(n));}catch(Exception e){error(e);}}).setNegativeButton("关闭",null).show();}catch(Exception e){error(e);}}
    private void editProject(JSONObject existing){LinearLayout form=ToolUi.column(context());EditText name=ToolUi.field(context(),form,"项目名称",existing==null?"":existing.optString("name"),false);CheckBox half=new CheckBox(context());half.setText("按 50% 分摊结算（AI报销）");half.setChecked(existing!=null&&existing.optString("settlement_mode").equals("half"));form.addView(half);CheckBox archived=new CheckBox(context());archived.setText("归档项目（保留记账数据）");archived.setChecked(existing!=null&&existing.optBoolean("archived"));form.addView(archived);if(existing!=null&&existing.optJSONObject("_conflicts").length()>0)action(form,"处理项目冲突",()->LedgerConflicts.show(context(),sync,"project",existing.optString("id"),this::render));
        AlertDialog dialog=new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle(existing==null?"创建项目组":"编辑项目组").setView(form).setPositiveButton("保存",null).setNegativeButton("取消",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{String value=name.getText().toString().trim();if(value.isEmpty())throw new IllegalArgumentException("请填写项目名称");JSONObject change=new JSONObject();if(existing==null||!value.equals(existing.optString("name")))change.put("name",value);String mode=half.isChecked()?"half":"general";if(existing==null||!mode.equals(existing.optString("settlement_mode")))change.put("settlement_mode",mode);if(existing==null||archived.isChecked()!=existing.optBoolean("archived"))change.put("archived",archived.isChecked());if(existing==null)change.put("created_at",System.currentTimeMillis()/1000.0);if(change.length()>0)sync.store().patch("project",existing==null?LedgerStore.id():existing.getString("id"),change,false,existing==null?new JSONArray():existing.getJSONArray("_heads"));sync.changed();dialog.dismiss();render();}catch(Exception e){error(e);}}));dialog.show();}
    private Spinner spinner(LinearLayout form,String label,String[] values,String selected){TextView caption=ToolUi.text(context(),label,13,ToolUi.MUTED);ToolUi.space(form,caption);Spinner s=ToolUi.spinner(context());s.setAdapter(ToolUi.choices(context(),values));s.setSelection(Math.max(0,Arrays.asList(values).indexOf(selected)));ToolUi.space(form,s);return s;}
    private void edit(JSONObject entity){try{original=entity==null?new JSONObject():new JSONObject(entity.toString());editingId=entity==null?LedgerStore.id():entity.getString("id");draft=new JSONObject(original.toString());showEditor();}catch(Exception e){error(e);}}
    private void showEditor(){try{
        LinearLayout form=ToolUi.column(context());form.setPadding(ToolUi.dp(context(),20),ToolUi.dp(context(),8),ToolUi.dp(context(),20),ToolUi.dp(context(),20));ScrollView scroll=new ScrollView(context());scroll.addView(form);
        title=ToolUi.field(context(),form,"名称",field(draft,"title",""),false);
        ToolUi.Grid grid=new ToolUi.Grid(context(),130,2,12);form.addView(grid);LinearLayout left=ToolUi.column(context()),right=ToolUi.column(context());grid.addView(left);grid.addView(right);
        amount=ToolUi.field(context(),left,"金额",field(draft,"amount",""),false);amount.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);
        currency=spinner(right,"币种",new String[]{"CNY","USD","EUR","HKD"},draft.optString("currency","CNY"));
        JSONArray groups=sync.store().list("project");List<String> names=new ArrayList<>();editProjectIds.clear();for(int i=0;i<groups.length();i++){JSONObject p=groups.getJSONObject(i);if(p.optBoolean("archived")&&!p.optString("id").equals(original.optString("project_id")))continue;names.add(p.optString("name"));editProjectIds.add(p.getString("id"));}project=spinner(left,"项目",names.toArray(new String[0]),"");if(editProjectIds.isEmpty())throw new IllegalArgumentException("请先创建或取消归档一个项目");project.setSelection(Math.max(0,editProjectIds.indexOf(draft.optString("project_id",selectedProject.equals("all")?LedgerStore.AI_PROJECT:selectedProject))));
        type=spinner(right,"收支",new String[]{"支出","收入"},draft.optString("entry_type").equals("income")?"收入":"支出");
        date=ToolUi.field(context(),left,"日期",field(draft,"date",LocalDate.now().toString()),false);dateField(date,()->{});category=ToolUi.field(context(),right,"分类",field(draft,"category","其他"),false);
        status=spinner(form,"报销状态",new String[]{"待报销","已报销","不报销"},draft.optString("status").equals("reimbursed")?"已报销":draft.optString("status").equals("non_reimbursable")?"不报销":"待报销");
        notes=ToolUi.field(context(),form,"备注",field(draft,"notes",""),false);notes.setSingleLine(false);notes.setMinLines(2);
        LinearLayout upload=new LinearLayout(context());upload.setGravity(Gravity.CENTER_VERTICAL);ToolUi.space(form,upload);upload.addView(ToolUi.text(context(),"附件",16,ToolUi.INK),new LinearLayout.LayoutParams(0,-2,1));upload.addView(ToolUi.iconButton(context(),"plus","添加附件",()->new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("添加附件").setItems(new String[]{"从相册选择","拍照","选择文件"},(d,which)->{if(which==0)gallery();else if(which==1)camera();else pick();}).show()));attachments=ToolUi.column(context());form.addView(attachments);renderAttachments();
        if(original.optJSONObject("_conflicts")!=null&&original.optJSONObject("_conflicts").length()>0)action(form,"处理并发修改",()->conflicts(original));
        AlertDialog dialog=new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle(original.has("id")?"编辑记账":"新增记账").setView(scroll).setPositiveButton("保存",null).setNegativeButton("取消",(d,w)->draft=null).setNeutralButton(original.has("id")?"删除":null,(d,w)->new com.google.android.material.dialog.MaterialAlertDialogBuilder(context()).setTitle("删除此记录？").setMessage("删除会同步到所有设备，离线旧版本不会恢复此记录。").setPositiveButton("删除",(a,b)->{try{sync.store().patch("entry",editingId,new JSONObject(),true);sync.changed();draft=null;render();}catch(Exception e){error(e);}}).setNegativeButton("取消",null).show()).create();
        dialog.setOnCancelListener(d->draft=null);dialog.setOnShowListener(d->{commitButton=dialog.getButton(-1);commitButton.setEnabled(importing==0);commitButton.setOnClickListener(v->{try{if(importing>0)return;capture();if(draft.getString("title").trim().isEmpty())throw new IllegalArgumentException("请填写名称");LocalDate.parse(draft.getString("date"));BigDecimal value=new BigDecimal(draft.getString("amount")).setScale(2,java.math.RoundingMode.UNNECESSARY);if((draft.optString("entry_type").equals("income")&&value.signum()<=0)||value.signum()<0||value.compareTo(new BigDecimal("999999999.99"))>0)throw new IllegalArgumentException("金额超出范围");draft.put("amount",value.toPlainString()).put("amount_minor",value.movePointRight(2).longValueExact());JSONObject changes=new JSONObject();for(String key:LedgerStore.keys(draft))if(!key.startsWith("_")&&!key.equals("id")&&!LedgerStore.equivalent(draft.opt(key),original.opt(key)))changes.put(key,draft.get(key));if(changes.has("amount")||changes.has("amount_minor")){changes.put("amount",draft.get("amount"));changes.put("amount_minor",draft.get("amount_minor"));}if(!original.has("id"))changes.put("created_at",System.currentTimeMillis()/1000.0);
            if(changes.length()>0)sync.store().patch("entry",editingId,changes,false,original.optJSONArray("_heads")==null?new JSONArray():original.getJSONArray("_heads"));sync.changed();draft=null;dialog.dismiss();render();}catch(Exception e){error(e);}});});dialog.show();
    }catch(Exception e){error(e);}}
    private void capture()throws Exception{if(draft==null||title==null)return;draft.put("title",title.getText().toString().trim()).put("date",date.getText().toString().trim()).put("amount",amount.getText().toString().trim()).put("project_id",editProjectIds.get(project.getSelectedItemPosition())).put("currency",currency.getSelectedItem().toString()).put("entry_type",type.getSelectedItemPosition()==1?"income":"expense").put("status",type.getSelectedItemPosition()==1?"not_applicable":new String[]{"waiting","reimbursed","non_reimbursable"}[status.getSelectedItemPosition()]).put("category",category.getText().toString()).put("notes",notes.getText().toString());}
    private void gallery(){try{capture();startActivityForResult(ToolUi.photoPicker(),703);}catch(Exception e){error(e);}}
    private void pick(){try{capture();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true).putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/jpeg","image/png","image/webp","application/pdf","application/ofd"});startActivityForResult(i,701);}catch(Exception e){error(e);}}
    private Uri sharedUri(String name){return new Uri.Builder().scheme("content").authority(getPackageName()+".ledger").appendPath(name).build();}
    private File shareDir(){File dir=new File(getCacheDir(),"ledger-shared");dir.mkdirs();return dir;}
    private void camera(){try{capture();cameraName=LedgerStore.id()+".jpg";File file=new File(shareDir(),cameraName);if(!file.createNewFile())throw new IOException("无法创建拍照文件");Uri uri=sharedUri(cameraName);Intent intent=new Intent(MediaStore.ACTION_IMAGE_CAPTURE).putExtra(MediaStore.EXTRA_OUTPUT,uri).addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);intent.setClipData(ClipData.newRawUri("photo",uri));startActivityForResult(intent,702);}catch(Exception e){error(e);}}
    @Override public void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK)return;if(request==702&&cameraName!=null){addAttachment(sharedUri(cameraName),"拍照-"+LocalDate.now()+".jpg");cameraName=null;}else if((request==701||request==703)&&data!=null){if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)addAttachment(data.getClipData().getItemAt(i).getUri(),null);else if(data.getData()!=null)addAttachment(data.getData(),null);}}
    private void addAttachment(Uri uri,String given){if(draft==null)return;final JSONObject destination=draft;final String entry=editingId;importing++;if(commitButton!=null)commitButton.setEnabled(false);renderAttachments();sync.submit(()->{File temp=null;try{String name=given;if(name==null)try(Cursor cursor=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())name=cursor.getString(0);}if(name==null)name="附件.pdf";temp=File.createTempFile("ledger-import-",".part",getCacheDir());try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(temp)){if(in==null)throw new IOException("无法读取附件");byte[] b=new byte[65536];int n;long total=0;while((n=in.read(b))!=-1){total+=n;if(total>50L*1024*1024)throw new IOException("附件上限 50 MB");out.write(b,0,n);}}JSONObject a=sync.store().attach(entry,temp,name,"receipt");runOnUiThread(()->{try{if(draft!=destination)return;draft.put("attachment:"+a.getString("id"),a);renderAttachments();}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->error(e));}finally{if(temp!=null)temp.delete();runOnUiThread(()->{importing=Math.max(0,importing-1);if(commitButton!=null)commitButton.setEnabled(importing==0);renderAttachments();});}});}
    private void renderAttachments(){if(attachments==null||draft==null)return;attachments.removeAllViews();if(importing>0)ToolUi.space(attachments,ToolUi.text(context(),"正在添加附件…",13,ToolUi.MUTED));for(String key:LedgerStore.keys(draft))if(key.startsWith("attachment:")&&!draft.isNull(key)){JSONObject a=draft.optJSONObject(key);LinearLayout row=new LinearLayout(context());row.setGravity(Gravity.CENTER_VERTICAL);TextView name=ToolUi.text(context(),a.optString("original_name"),14,ToolUi.BLUE);name.setMaxLines(2);name.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);name.setPadding(ToolUi.dp(context(),8),ToolUi.dp(context(),12),ToolUi.dp(context(),8),ToolUi.dp(context(),12));name.setOnClickListener(v->openAttachment(a));row.addView(name,new LinearLayout.LayoutParams(0,-2,1));row.addView(ToolUi.iconButton(context(),"close","移除附件 "+a.optString("original_name"),()->{try{draft.put(key,JSONObject.NULL);renderAttachments();}catch(Exception e){error(e);}}));ToolUi.space(attachments,row);}}
    private void openAttachment(JSONObject a){sync.submit(()->{try{String path=a.getString("relative_path");String ext=path.substring(path.lastIndexOf('.'));String name=LedgerStore.id()+ext;File source=new File(sync.store().blobs,a.getString("sha256")),copy=new File(shareDir(),name);if(source.length()!=a.getLong("size")||!LedgerStore.hash(source).equals(a.getString("sha256")))throw new IOException("附件完整性校验失败，请重新同步");java.nio.file.Files.copy(source.toPath(),copy.toPath());runOnUiThread(()->{try{startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(sharedUri(name),RelayProvider.mime(name)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->error(e));}});}
    private void conflicts(JSONObject entity){LedgerConflicts.show(context(),sync,"entry",entity.optString("id"),this::render);}
    @Override public void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("selectedProject",selectedProject);out.putString("cameraName",cameraName);try{capture();if(draft!=null){out.putString("draft",draft.toString());out.putString("original",original.toString());out.putString("editingId",editingId);}}catch(Exception ignored){}}
    @Override protected void onPageResume(){handler.post(refresh);}
    @Override protected void onPagePause(){handler.removeCallbacks(refresh);}
}
