package net.lanbridge.android;
import android.content.*;
import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import org.json.*;

/** On-device Keystore and preference transaction checks; no network requests. */
final class ConfigBackupInstrumentation {
 static int assertions;
 static void check(boolean value,String detail){assertions++;if(!value)throw new AssertionError(detail);}
 static Object invoke(String name,Class<?>[] types,Object... args)throws Exception{Method m=ConfigBackupService.class.getDeclaredMethod(name,types);m.setAccessible(true);return m.invoke(null,args);}
 static JSONObject state(Context c)throws Exception{return (JSONObject)invoke("state",new Class<?>[]{Context.class},c);}
 static ConfigBackupService.Preview preview(Context c,JSONObject value)throws Exception{return (ConfigBackupService.Preview)invoke("previewValue",new Class<?>[]{Context.class,JSONObject.class,JSONObject.class},c,value,state(c));}
 static JSONObject ai(String key,boolean parcel)throws Exception{JSONObject roles=new JSONObject().put("chat",new JSONObject().put("provider_id","fixture").put("model","chat-test"));if(parcel)roles.put("parcel",new JSONObject().put("provider_id","fixture").put("model","parcel-test"));return new JSONObject().put("format",AiConfigCodec.FORMAT).put("version",1).put("providers",new JSONArray().put(new JSONObject().put("id","fixture").put("name","Test").put("kind","openai").put("base_url","https://fixture.invalid/v1"))).put("roles",roles).put("secrets",new JSONObject().put("fixture",key));}
 static String run(Context context)throws Exception{
  assertions=0;String[] names={"MainActivity","profile","ai-config","webdav-profile","webdav-layout","parcel-local","config-restore-journal"};Map<String,Map<String,?>> initial=new HashMap<>();for(String name:names)initial.put(name,new HashMap<>(context.getSharedPreferences(name,0).getAll()));
  try{
   WebDavSettings.store(context).save("https://fixture.invalid/dav","fixture","backup-test-password","");WebDavSettings.root(context);String identity=WebDavSettings.identity(context);AiSettings settings=new AiSettings(context);settings.importSnapshot(ai("local-key-for-test",true),settings.revision());settings.setEnabled(false);context.getSharedPreferences("MainActivity",0).edit().putBoolean("favorite.ledger",false).commit();new LoginStore(context).save("https://nas.invalid","local-user","private-nas-password","lan");int ledgerCount=new LedgerStore(new File(context.getFilesDir(),"ledger-v1")).operations().size();
   JSONObject windows=ConfigBackupCodec.payload("windows",new JSONObject().put("settings.json",new JSONObject().put("theme","dark")),ai("incoming-key-for-test",false));ConfigBackupService.Preview cross=preview(context,windows);check(cross.summary.contains("仅导入"),"Cross platform preview unclear");File recovery=ConfigBackupService.restore(context,cross);check(recovery.isFile(),"Encrypted recovery missing");JSONObject restored=settings.exportSnapshot();String preserved=restored.getJSONObject("roles").getJSONObject("parcel").getString("provider_id");check(!preserved.equals("fixture"),"Colliding local provider was not cloned");check(restored.getJSONObject("secrets").getString(preserved).equals("local-key-for-test"),"Local parcel key lost");check(restored.getJSONObject("secrets").getString("fixture").equals("incoming-key-for-test"),"Incoming shared key lost");check(!context.getSharedPreferences("MainActivity",0).getBoolean("favorite.ledger",true),"Windows changed Android preference");check(new LoginStore(context).username().equals("local-user"),"Windows changed NAS account");check(!settings.enabled(),"Restore enabled SMS upload");check(WebDavSettings.identity(context).equals(identity),"Restore changed active connection");String ciphertext=new String(java.nio.file.Files.readAllBytes(recovery.toPath()),java.nio.charset.StandardCharsets.UTF_8);check(!ciphertext.contains("local-key-for-test")&&!ciphertext.contains("private-nas-password"),"Plaintext key in recovery");check(ConfigBackupCodec.decrypt(new JSONObject(ciphertext),"backup-test-password").getJSONObject("ai").getJSONObject("secrets").getString("fixture").equals("local-key-for-test"),"Recovery not decryptable");
   JSONObject android=ConfigBackupCodec.payload("android",AndroidConfigBackup.create(new JSONObject().put("favorite.ledger",true),"https://restored.invalid","restored-user","all"),ai("restored-key",false));ConfigBackupService.restore(context,preview(context,android));check(context.getSharedPreferences("MainActivity",0).getBoolean("favorite.ledger",false),"Android home not restored");check(new LoginStore(context).username().equals("restored-user"),"Android NAS not restored");check(!new LoginStore(context).hasPassword(),"NAS old password attached to new account");
   ConfigBackupService.Preview stale=preview(context,windows);context.getSharedPreferences("MainActivity",0).edit().putBoolean("favorite.ledger",false).commit();try{ConfigBackupService.restore(context,stale);throw new AssertionError("Concurrent change accepted");}catch(IOException expected){check(expected.getMessage().contains("变化"),"Wrong stale error");}
   JSONObject before=state(context);AtomicBoolean fail=new AtomicBoolean(true);Context broken=new ContextWrapper(context){@Override public Context getApplicationContext(){return this;}@Override public SharedPreferences getSharedPreferences(String name,int mode){SharedPreferences real=super.getSharedPreferences(name,mode);if(!name.equals("ai-config"))return real;return (SharedPreferences)Proxy.newProxyInstance(SharedPreferences.class.getClassLoader(),new Class<?>[]{SharedPreferences.class},(proxy,method,args)->{Object result=method.invoke(real,args);if(!method.getName().equals("edit"))return result;SharedPreferences.Editor editor=(SharedPreferences.Editor)result;return Proxy.newProxyInstance(SharedPreferences.Editor.class.getClassLoader(),new Class<?>[]{SharedPreferences.Editor.class},(ep,em,ea)->{if(em.getName().equals("commit")&&fail.compareAndSet(true,false))return false;Object ret=em.invoke(editor,ea);return ret instanceof SharedPreferences.Editor?ep:ret;});});}};
   try{ConfigBackupService.restore(broken,android);throw new AssertionError("Failed write accepted");}catch(IOException expected){check(!fail.get(),"Failure injection never ran");}check(LedgerStore.equivalent(before,state(context)),"Partial config restore was not rolled back");
   JSONObject raw=(JSONObject)invoke("raw",new Class<?>[]{Context.class,String[].class},context,new String[]{"MainActivity","profile","ai-config"});new LoginStore(context,"config-restore-journal","config-restore-journal-v1").save("configuration-restore","local",raw.toString(),"");context.getSharedPreferences("MainActivity",0).edit().putBoolean("favorite.ledger",true).commit();ConfigBackupService.recoverPending(context);check(!context.getSharedPreferences("MainActivity",0).getBoolean("favorite.ledger",true),"Interrupted restore did not recover");check(!new LoginStore(context,"config-restore-journal","config-restore-journal-v1").hasPassword(),"Recovery journal not cleared");
   JSONObject legacy=AndroidConfigBackup.create(new JSONObject().put("favorite.ledger",true),"https://legacy.invalid","legacy","lan");String aiBefore=settings.exportSnapshot().toString();ConfigBackupService.restore(context,legacy);check(new LoginStore(context).username().equals("legacy"),"Old Android backup unsupported");check(settings.exportSnapshot().toString().equals(aiBefore),"Old Android backup changed AI");check(new LedgerStore(new File(context.getFilesDir(),"ledger-v1")).operations().size()==ledgerCount,"Configuration restore changed ledger");
   return "PASS: "+assertions+" unified configuration transaction assertions";
  }finally{for(String name:names){SharedPreferences.Editor edit=context.getSharedPreferences(name,0).edit().clear();for(Map.Entry<String,?> e:initial.get(name).entrySet()){Object v=e.getValue();if(v instanceof Boolean)edit.putBoolean(e.getKey(),(Boolean)v);else if(v instanceof Integer)edit.putInt(e.getKey(),(Integer)v);else if(v instanceof Long)edit.putLong(e.getKey(),(Long)v);else if(v instanceof Float)edit.putFloat(e.getKey(),(Float)v);else if(v instanceof Set)edit.putStringSet(e.getKey(),(Set<String>)v);else edit.putString(e.getKey(),(String)v);}edit.commit();}}
 }
}
