package net.lanbridge.android;
import android.content.*;
import android.os.Bundle;
import org.json.*;
import java.io.*;
import java.util.*;

/** Synthetic real-WebDAV exchange bridge; never included in release APK. */
final class ConfigBackupExchange {
 private static int checks;
 private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
 private static JSONObject ai(String id,String key,String model,boolean parcel)throws Exception{JSONObject role=new JSONObject().put("provider_id",id).put("model",model);JSONObject roles=new JSONObject().put("chat",role);if(parcel)roles.put("parcel",new JSONObject().put("provider_id",id).put("model","android-parcel-model"));return new JSONObject().put("format",AiConfigCodec.FORMAT).put("version",1).put("providers",new JSONArray().put(new JSONObject().put("id",id).put("name","Synthetic exchange").put("kind","openai").put("base_url","https://fixture.invalid/v1"))).put("roles",roles).put("secrets",new JSONObject().put(id,key));}
 static String run(Context context,Bundle args)throws Exception{
  checks=0;String[] names={"MainActivity","profile","ai-config","webdav-profile","webdav-layout","parcel-local","config-restore-journal","relay","ledger"};Map<String,Map<String,?>> original=new LinkedHashMap<>();for(String name:names)original.put(name,new HashMap<>(context.getSharedPreferences(name,0).getAll()));
  try{
   String url=args.getString("url"),root=args.getString("root","ConfigFixture"),user=args.getString("user","user"),password=args.getString("password","pass"),mode=args.getString("mode","upload");if(url==null)throw new IOException("Fixture URL required");
   // Set isolated fixture state without creating migration tasks for the device's real connection.
   context.getSharedPreferences("webdav-layout",0).edit().clear().putString("root",root).putBoolean("unified_v2",true).commit();context.getSharedPreferences("relay",0).edit().putBoolean("shared_migrated",true).commit();WebDavSettings.store(context).save(url,user,password,"");
   AiSettings settings=new AiSettings(context);settings.setEnabled(false);context.getSharedPreferences("MainActivity",0).edit().putBoolean("favorite.ledger",false).commit();new LoginStore(context).save("https://android-nas.invalid","android-local-user","synthetic-nas-password","lan");String identity=WebDavSettings.identity(context);int operations=new LedgerStore(new File(context.getFilesDir(),"ledger-v1")).operations().size();String filename;
   if(mode.equals("upload")){
    settings.importSnapshot(ai("android-fixture","android-fixture-key","android-fixture-model",true),settings.revision());filename=ConfigBackupService.upload(context);RelayDav.Entry uploaded=null;for(RelayDav.Entry e:ConfigBackupService.list(context))if(e.name.equals(filename))uploaded=e;check(uploaded!=null,"Uploaded Android snapshot not listed");JSONObject roundtrip=ConfigBackupService.download(context,uploaded);check(roundtrip.getString("platform").equals("android"),"Uploaded snapshot platform wrong");check(roundtrip.getJSONObject("ai").getJSONObject("secrets").getString("android-fixture").equals("android-fixture-key"),"Uploaded AI key did not roundtrip");check(!roundtrip.getJSONObject("config").toString().contains("synthetic-nas-password"),"NAS password leaked into config");
   }else if(mode.equals("restore")){
    String id=args.getString("expected_provider","fixture"),key=args.getString("expected_key","pc-fixture-key"),model=args.getString("expected_model","pc-fixture-model");settings.importSnapshot(ai(id,"android-local-key","android-local-chat",true),settings.revision());String wanted=args.getString("filename","");RelayDav.Entry selected=null;for(RelayDav.Entry e:ConfigBackupService.list(context)){if(wanted.isEmpty()?e.name.startsWith("config-windows-"):e.name.equals(wanted)){selected=e;break;}}check(selected!=null,"Windows snapshot not found");filename=selected.name;ConfigBackupService.Preview preview=ConfigBackupService.preview(context,selected);check(preview.platform.equals("windows"),"Selected snapshot is not Windows");check(preview.summary.contains("仅导入"),"Cross-platform preview missing");ConfigBackupService.restore(context,preview);JSONObject restored=settings.exportSnapshot();check(restored.getJSONObject("secrets").getString(id).equals(key),"PC AI key mismatch");check(restored.getJSONObject("roles").getJSONObject("chat").getString("model").equals(model),"PC chat model mismatch");String retained=restored.getJSONObject("roles").getJSONObject("parcel").getString("provider_id");check(!retained.equals(id),"Local colliding parcel provider was not cloned");check(restored.getJSONObject("secrets").getString(retained).equals("android-local-key"),"Local parcel key lost");check(restored.getJSONObject("roles").getJSONObject("parcel").getString("model").equals("android-parcel-model"),"Local parcel model lost");check(!context.getSharedPreferences("MainActivity",0).getBoolean("favorite.ledger",true),"Windows overwrote Android preference");check(new LoginStore(context).username().equals("android-local-user"),"Windows overwrote local NAS account");
   }else throw new IOException("Unknown exchange mode");
   check(identity.equals(WebDavSettings.identity(context)),"Exchange changed fixture connection");check(!settings.enabled(),"Exchange enabled SMS upload");check(new LedgerStore(new File(context.getFilesDir(),"ledger-v1")).operations().size()==operations,"Exchange changed ledger data");return new JSONObject().put("status","PASS").put("mode",mode).put("filename",filename).put("checks",checks).toString();
  }finally{for(Map.Entry<String,Map<String,?>> prefs:original.entrySet()){SharedPreferences.Editor editor=context.getSharedPreferences(prefs.getKey(),0).edit().clear();for(Map.Entry<String,?> e:prefs.getValue().entrySet()){Object v=e.getValue();if(v instanceof Boolean)editor.putBoolean(e.getKey(),(Boolean)v);else if(v instanceof Integer)editor.putInt(e.getKey(),(Integer)v);else if(v instanceof Long)editor.putLong(e.getKey(),(Long)v);else if(v instanceof Float)editor.putFloat(e.getKey(),(Float)v);else if(v instanceof Set)editor.putStringSet(e.getKey(),(Set<String>)v);else editor.putString(e.getKey(),(String)v);}if(!editor.commit())throw new IOException("Fixture preferences restore failed");}}
 }
}
