package net.lanbridge.android;
import android.content.Context;
import org.json.*;
import java.io.IOException;
import java.util.*;

/** Native SQLite integration with synthetic data in a disposable, uniquely named test database. */
public final class ParcelInstrumentation {
    private static int checks;
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    private static ParcelSms.Message sms(String id,long date,String body){return new ParcelSms.Message(id,date,"106000",body);}
    private static ParcelAi.Item item(String source,String code,String tracking,String carrier,String location,String locker,String status){return new ParcelAi.Item(List.of(source),code,tracking,carrier,location,locker,status,null);}
    public static String run(Context context)throws Exception{
        checks=0;String name="parcel-test-"+UUID.randomUUID()+".db";ParcelStore store=new ParcelStore(context,name);long now=System.currentTimeMillis();
        try{
            ParcelSms.Message first=sms("1",now,"中通，运单TRACK001，取件码1234，北门驿站A柜");ParcelAi.Item original=item("1","1234","TRACK001","中通","北门驿站","A柜",ParcelAi.PENDING);check(store.ingest(List.of(first),List.of(original))==1,"Initial insert");check(store.list(false,"address").size()==1,"Pending list");check(store.ingest(List.of(first),List.of(original))==0,"Idempotent reingest");check(store.pendingSources(List.of(first)).isEmpty(),"Processed SMS repeated");String id=store.list(false,"newest").get(0).id;
            store.setCollected(id,true);ParcelSms.Message reminder=sms("2",now+1000,"中通，运单TRACK001，取件码1234，北门驿站A柜提醒");store.ingest(List.of(reminder),List.of(item("2","1234","TRACK001","中通","北门驿站","A柜",ParcelAi.PENDING)));check(store.list(false,"address").isEmpty(),"Manual archive resurrected");check(store.list(true,"carrier").get(0).manualCollected,"Manual flag lost");check(store.list(true,"carrier").get(0).sources.size()==2,"Missing source relation");store.setCollected(id,false);check(store.list(false,"locker").size()==1,"Undo archive failed");
            ParcelSms.Message done=sms("3",now+2000,"中通，运单TRACK001，已取件");store.ingest(List.of(done),List.of(item("3","","TRACK001","中通","北门驿站","A柜",ParcelAi.COLLECTED)));check(store.list(true,"newest").size()==1,"AI collection not archived");
            ParcelSms.Message a=sms("4",now,"申通取件码7788南门A柜"),b=sms("5",now+200,"申通取件码7788南门B柜");store.ingest(List.of(a,b),List.of(item("4","7788","","申通","南门","A柜",ParcelAi.PENDING),item("5","7788","","申通","南门","B柜",ParcelAi.PENDING)));check(store.list(false,"address").size()==2,"Same code different lockers merged");
            ParcelSms.Message no1=sms("6",now,"包裹已到北门驿站，未提供取件码"),no2=sms("7",now+300,"另一包裹已到北门驿站，未提供取件码");store.ingest(List.of(no1,no2),List.of(item("6","","","","北门驿站","",ParcelAi.PENDING),item("7","","","","北门驿站","",ParcelAi.PENDING)));check(store.list(false,"address").size()==4,"Missing codes merged");
            ParcelSms.Message repeat=sms("8",now+1000,"申通取件码7788南门A柜请尽快取件");store.ingest(List.of(repeat),List.of(item("8","7788","","申通","南门","A柜",ParcelAi.PENDING)));check(store.list(false,"address").size()==4,"Identifiable reminder duplicated");ParcelSms.Message later=sms("9",now+32L*86400000,"申通取件码7788南门A柜新包裹");store.ingest(List.of(later),List.of(item("9","7788","","申通","南门","A柜",ParcelAi.PENDING)));check(store.list(false,"address").size()==5,"Time window ignored");
            ParcelSms.Message bad1=sms("10",now,"取件码6060在西门"),bad2=sms("11",now,"普通私人消息");int before=store.list(false,"newest").size();try{store.ingest(List.of(bad1,bad2),List.of(item("10","6060","","","西门","",ParcelAi.PENDING),item("11","HALLUCINATED","","","","",ParcelAi.PENDING)));throw new AssertionError("Invalid extraction accepted");}catch(IOException expected){}check(store.pendingSources(List.of(bad1,bad2)).size()==2,"Failed batch marked processed");check(store.list(false,"newest").size()==before,"Failed batch partially wrote rows");
            ParcelSms.Message other=sms("12",now,"非快递私人内容"),delivery=sms("13",now,"快递正在派送");store.ingest(List.of(other,delivery),List.of(item("12","","","","","",ParcelAi.OTHER),item("13","","","","","",ParcelAi.DELIVERY)));check(store.pendingSources(List.of(other,delivery)).isEmpty(),"Handled non-arrival sources not remembered");check(store.list(false,"newest").size()==before,"Delivery/non-parcel incorrectly stored");
            ParcelSms.Message tx1=sms("tx1",now,"取件码TX100西门"),tx2=sms("tx2",now,"取件码TX200东门");store.getWritableDatabase().execSQL("CREATE TRIGGER reject_test BEFORE INSERT ON parcels WHEN NEW.code='TX200' BEGIN SELECT RAISE(ABORT,'synthetic constraint'); END");try{store.ingest(List.of(tx1,tx2),List.of(item("tx1","TX100","","","西门","",ParcelAi.PENDING),item("tx2","TX200","","","东门","",ParcelAi.PENDING)));throw new AssertionError("Synthetic DB failure expected");}catch(IOException expected){}check(store.list(false,"newest").size()==before,"Transaction failure left partial parcel");check(store.pendingSources(List.of(tx1,tx2)).size()==2,"Transaction failure left processed markers");store.getWritableDatabase().execSQL("DROP TRIGGER reject_test");
            store.close();store=new ParcelStore(context,name);check(store.list(true,"newest").size()==1&&store.list(false,"newest").size()==5,"Records not durable");
            ParcelSms.Message photo=new ParcelSms.Message("image:test",now,"图片","说明",ParcelSms.sha256(new byte[]{1,2,3}));JSONObject row=new JSONObject().put("source_ids",new JSONArray().put(photo.id)).put("code","P123").put("tracking_number","").put("carrier","中通").put("location","图中地址").put("locker","").put("status",ParcelAi.PENDING).put("deadline",JSONObject.NULL);List<ParcelAi.Item> recognized=ParcelAi.parseResponse(new JSONObject().put("items",new JSONArray().put(row)).toString(),List.of(photo));store.ingest(List.of(photo),recognized);check(store.pendingSources(List.of(photo)).isEmpty(),"Selected image should be imported directly");check(store.ingest(List.of(photo),recognized)==0,"Repeated image should be deduplicated");
            ParcelSms.Message lateReminder=sms("late-auto",now+10000,"中通，运单TRACK001，取件码1234，北门驿站A柜又提醒");store.ingest(List.of(lateReminder),List.of(item("late-auto","1234","TRACK001","中通","北门驿站","A柜",ParcelAi.PENDING)));boolean stayedArchived=false;for(ParcelStore.Parcel parcel:store.list(true,"newest"))if(parcel.id.equals(id))stayedArchived=true;check(stayedArchived,"Automatic completed state resurrected");
            ParcelSms.Message oldNoTrack=sms("old-archived",now,"取件码9090东门C柜");store.ingest(List.of(oldNoTrack),List.of(item("old-archived","9090","","","东门","C柜",ParcelAi.PENDING)));String archivedId=null;for(ParcelStore.Parcel parcel:store.list(false,"newest"))if(parcel.code.equals("9090"))archivedId=parcel.id;store.setCollected(archivedId,true);ParcelSms.Message reused=sms("new-reused",now+1000,"新包裹取件码9090东门C柜");store.ingest(List.of(reused),List.of(item("new-reused","9090","","","东门","C柜",ParcelAi.PENDING)));ParcelStore.Parcel candidate=null;for(ParcelStore.Parcel parcel:store.list(false,"newest"))if(parcel.code.equals("9090"))candidate=parcel;check(candidate!=null&&candidate.needsReview&&!candidate.id.equals(archivedId),"Reused code hidden in old archive");check(candidate.sources.get(0).id.equals("new-reused"),"Ambiguous source attached to wrong package");
            ParcelSms.Message multiA=sms("ma",now,"取件码3131北门"),multiB=sms("mb",now,"取件码4141北门");ParcelAi.Item badMerge=new ParcelAi.Item(List.of("ma","mb"),"3131","","","北门","",ParcelAi.PENDING,null);try{store.ingest(List.of(multiA,multiB),List.of(badMerge));throw new AssertionError("Cross-package merge accepted");}catch(IOException expected){}check(store.pendingSources(List.of(multiA,multiB)).size()==2,"Cross-package merge consumed source");store.ingest(List.of(multiA,multiB),List.of(item("ma","3131","","","北门","",ParcelAi.PENDING),item("mb","4141","","","北门","",ParcelAi.PENDING)));int split=0;for(ParcelStore.Parcel parcel:store.list(false,"newest"))if(parcel.code.equals("3131")||parcel.code.equals("4141"))split++;check(split==2,"Different complete codes merged");
            return "PASS: "+checks+" parcel SQLite assertions; idempotency, references, dedup, archive/undo, atomic failure and direct photo import";
        }finally{store.close();context.deleteDatabase(name);}
    }
}
